# Read Data

In [3]:
#Read data file

import pandas as pd

filepath = "dataset/balanced_dataset2_protection_duration.csv"
df = pd.read_csv(filepath)
df

,page_id,page_title,view_count,protection_status,page_length,edit_count,page_watchers,page_watchers_recent_edits,page_views_past_30days,page_id_scrapped,redirects,recent_number_of_edits,number_distinct_authors,number_categories
0,649497,Ten High,66388,unprotected,2942,129,25,4,488,649497,0,0,0,2
1,32289827,The Gravy Train,56091,unprotected,3424,40,25,5,652,32289827,0,0,0,2
2,17144344,German occupation of Estonia during World War I,45499,unprotected,8494,111,25,5,344,17144344,2,0,0,2
3,8035336,Wig wag (truck braking systems),45452,unprotected,64,28,25,5,204,8035336,0,0,0,2
4,38309501,List of theatres in Serbia,8509,unprotected,5604,24,25,12,24,38309501,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,49078342,Tony Krolis,558,unprotected,0,2932,25,21,0,0,0,6,3,78
829,23493896,Jindal Group,363464,sysop,0,2932,25,31,0,0,0,6,3,78
830,25198426,Mysandbox,1067,sysop,0,2932,25,32,0,0,0,6,3,78
831,3284182,List of spells in Harry Potter,2208118,sysop,0,2932,416,36,0,0,0,6,3,78
832,0,1848â€“49_massacres_in_Transylvania,1,sysop,0,2932,25,50,0,0,0,6,3,78

# Define helper functions

In [1]:
#Get current protection status of article 

def get_protection_status(title):
    
    import requests
    S = requests.Session()

    URL = "https://en.wikipedia.org/w/api.php"

    PARAMS = {
        "action": "query",
        "format": "json",
        "titles": title,
    #     "list": "protectedtitles",
        "prop": "info",
        "inprop": "protection"
    }

    R = S.get(url=URL, params=PARAMS)
    DATA = R.json()

    PAGES = DATA["query"]["pages"]
    
    for k, v in PAGES.items():
        if v['protection'] != []:
            protection_status = v["protection"][0]['level'] 
            protection_expiry = v["protection"][0]['expiry']
            print('Protection status = ',protection_status)
            print('Protection duration =', protection_expiry)
            return protection_status

In [2]:
title = 'Best Korea',
protection_status = get_protection_status(title)
print("Title: ", title, "Protection Status:", protection_status)

Protection status =  sysop
Protection duration = infinity
Title:  ('Best Korea',) Protection Status: sysop